---
name: "Check spelling"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  default:
    uses: Hapag-Lloyd/Repository-Templates/.github/workflows/default_spelling_callable.yml@1ae9a1d69c582281b4312e7ca65632adb32ddee8
    secrets: inherit
